# Generated by Django 2.0.6 on 2018-08-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timehutBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeekabooCollectionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='timehutBlog.PeekabooCollection')),
            ],
            options={
                'db_table': 'peekaboo_collection_comment',
                'ordering': ('created_at',),
                'managed': True,
            },
        ),
    ]
